import { DefaultTheme } from "styled-components";

export const theme: DefaultTheme = {
  dark: {
    primaryColor: "#3F51B5",
    primaryColorDark: "#303F9F",
    primaryColorLight: "#DFDFF1",
    generalBackground: "#181918",
    primaryColorText: "#FFFFFF",
    primaryTextColor: "#d7d7d8",
    secondaryTextColor: "#A6A6A6",
    accentColor: "#4fA7ff",
  },
  light: {
    primaryColor: "#3F51B5",
    primaryColorDark: "#303F9F",
    primaryColorLight: "#DFDFF1",
    primaryColorText: "#FFFFFF",
    primaryTextColor: "#151515",
    secondaryTextColor: "#575757",
    generalBackground: "#FAFAFA",
    accentColor: "#0F67FF",
  },
  fontSizes: [
    "12px",
    "14px",
    "16px",
    "18px",
    "20px",
    "22px",
    "24px",
    "28px",
    "32px",
    "36px",
    "40px",
    "48px",
    "56px",
  ],
  spacing: ["4px", "8px", "12px", "16px", "20px"],
};
